---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/kapp --version
      register: kapp_test_output
    - name: kapp --version
      debug:
        msg: '{{ kapp_test_output.stdout }}'
